language: ruby
sudo: false
cache: bundler
dist: trusty

# Early warning system to catch if Rubygems breaks something
before_install:
  - gem update --system $(grep rubygems omnibus_overrides.rb | cut -d'"' -f2)
  - gem --version
  - rvm @global do gem uninstall bundler -a -x || true
  - gem install bundler -v $(grep bundler omnibus_overrides.rb | cut -d'"' -f2)
  - bundle --version
  - rm -f .bundle/config

before_script:
 # force all .rspec tests into progress display to reduce line count
 - echo --color > .rspec
 - echo -fp >> .rspec
 # necessary for sudo: true tests, ingore failures on tests invoked with sudo: false
 - sudo sed -i -e 's/^Defaults\tsecure_path.*$//' /etc/sudoers || true

# do not run expensive spec tests on PRs, only on branches
branches:
  only:
  - master
  - chef-12

env:
  global:
    - FORCE_FFI_YAJL=ext

matrix:
  include:
  - rvm: 2.3.3
    sudo: true
    script: sudo -E $(which bundle) exec rake spec:unit;
    # also remove integration / external tests
    bundler_args: --without ci docgen guard integration maintenance omnibus_package --frozen
  - rvm: 2.4.1
    sudo: true
    script: sudo -E $(which bundle) exec rake sped:unit;
    # also remove integration / external tests
    bundler_args: --without ci docgen guard integration maintenance omnibus_package --frozen

notifications:
  on_change: true
  on_failure: true
  on_success: change
  on_pull_requests: false
  irc:
    channels:
    - chat.freenode.net#chef-hacking
